#!/usr/bin/env ruby
 
require 'rubygems'
require 'grit'
require 'rest-client'
 
old_rev, new_rev, ref_name = STDIN.gets.split

repo_name = File.basename(Dir.getwd)

puts "=============================="
puts "repo_name: " + repo_name + ""
puts "old_rev: " +  old_rev + ""
puts "new_rev: " + new_rev + ""
puts "ref_name: " + ref_name + ""
puts "=============================="

repo = Grit::Repo.new(".")
# this is the head so we expect only one commit
commit = repo.commits(new_rev,1).last

transactionId = nil

puts "=============================="
puts commit.id + ""
puts commit.message + ""
commit.message.each_line do |line| 
  if line.start_with?("Transaction-Id:") 
    line["Transaction-Id:"] = ""
    line.strip
    transactionId = line
    puts "!!!!!!!!!!!!!found " + transactionId + "!!!!!!!!!!!!!!!"
  end
end
puts "=============================="

if transactionId.nil?
  exit 1
end

puts "=============================="
puts "Exec rest call"
puts "=============================="

response = RestClient.get 'http://localhost:4567/transaction?repository=' + repo_name + '&commit=' + new_rev + '&transaction='

puts "=============================="
puts "Finished rest call"
puts "=============================="

#exit 1

